CREATE DATABASE DB_FOR_GROUP_BY;
USE DB_FOR_GROUP_BY;

CREATE TABLE EMPLOYEE (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    E_NAME VARCHAR(50),
    DEPRATMENT VARCHAR(50),
    SALARY DECIMAL(10,2),
    JOINING_DATE DATE
);    

INSERT INTO EMPLOYEE (E_NAME,DEPRATMENT,SALARY,JOINING_DATE) VALUES
('Alice', 'HR', '50000', '2020-06-15'),
('Bob', 'HR', '55000', '2019-04-02'),
('Charlie', 'IT', '70000', '2018-07-12'),
('David', 'IT', '72000', '2017-06-29'),
('Eve', 'IT', '73000', '2021-02-15');


SELECT * FROM EMPLOYEE;

-- Example 1: Count Employee in Each Department 

SELECT DEPRATMENT, COUNT(DEPRATMENT) FROM EMPLOYEE GROUP BY DEPRATMENT;

SELECT DEPRATMENT, AVG(SALARY) FROM EMPLOYEE GROUP BY DEPRATMENT;

SELECT DEPRATMENT , max(SALARY), min(SALARY) FROM EMPLOYEE GROUP BY DEPRATMENT;

SELECT DEPRATMENT, year(JOINING_DATE), COUNT(*) FROM EMPLOYEE GROUP BY DEPRATMENT, YEAR(JOINING_DATE);

SELECT DEPRATMENT, AVG(SALARY) AS AVG_SALARY
FROM EMPLOYEE
GROUP BY DEPRATMENT
ORDER BY AVG_SALARY DESC;


SELECT count(*),
	CASE
		WHEN salary < 60000 THEN 'Low salary'
        WHEN salary BETWEEN 60000 AND 70000 THEN 'Medium salary'
        ELSE 'High salary'
	END AS salary_range
FROM EMPLOYEE group by salary_range;


SELECT DEPRATMENT, COUNT(*) AS TOTAL_EMPLOYEE FROM EMPLOYEE group by DEPRATMENT ORDER BY TOTAL_EMPLOYEE DESC LIMIT 1;


SELECT DEPRATMENT, COUNT(*) AS TOTAL_EMPLOYEE FROM EMPLOYEE GROUP BY DEPRATMENT HAVING TOTAL_EMPLOYEE > 2;









